project = "qsexisting"
location = "West Europe"
quick_scan_storage_account_name = " adminteststr001 "
quick_scan_storage_account_container_name = "dergi"
quick_scan_storage_account_resource_group = "RG_Admin"
